# Generated by Django 3.1.1 on 2020-10-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='NAME')),
                ('age', models.CharField(blank=True, max_length=100, verbose_name='AGE')),
                ('address', models.CharField(max_length=200, verbose_name='ADDRESS')),
                ('tel', models.CharField(max_length=100, verbose_name='TEL')),
                ('email', models.EmailField(max_length=100, verbose_name='EMAIL')),
                ('birth', models.DateTimeField(verbose_name='BIRTH')),
            ],
        ),
    ]
